[gdrive]
type = drive
client_id = 
client_secret = 
scope = drive
token = {"access_token":"YOUR_ACCESS_TOKEN","token_type":"Bearer","refresh_token":"YOUR_REFRESH_TOKEN","expiry":"2026-04-21T15:00:00Z"}
team_drive =
